package fr.polytech.polydiploma.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-04-12T12:08:08.316+02:00
 * Generated source version: 3.1.10
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/pay", name = "PayWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PayWebService {

    @WebMethod
    @RequestWrapper(localName = "pay", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/pay", className = "fr.polytech.polydiploma.stubs.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/pay", className = "fr.polytech.polydiploma.stubs.PayResponse")
    @WebResult(name = "has_pay", targetNamespace = "")
    public boolean pay(
            @WebParam(name = "paiement", targetNamespace = "")
                    fr.polytech.polydiploma.stubs.Paiement paiement
    );
}
