package fr.polytech.polydiploma.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-04-12T12:08:08.358+02:00
 * Generated source version: 3.1.10
 */
@WebServiceClient(name = "PayWebServiceImplService",
        wsdlLocation = "file:/D:/Developpement/Projets/PolyDiploma/ClientCompta/src/main/resources/PayWS.wsdl",
        targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/pay")
public class PayWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/polydiploma/pay", "PayWebServiceImplService");
    public final static QName PayWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/polydiploma/pay", "PayWebServiceImplPort");

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Developpement/Projets/PolyDiploma/ClientCompta/src/main/resources/PayWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PayWebServiceImplService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "file:/D:/Developpement/Projets/PolyDiploma/ClientCompta/src/main/resources/PayWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PayWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PayWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PayWebServiceImplService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PayWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PayWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns PayWebService
     */
    @WebEndpoint(name = "PayWebServiceImplPort")
    public PayWebService getPayWebServiceImplPort() {
        return super.getPort(PayWebServiceImplPort, PayWebService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns PayWebService
     */
    @WebEndpoint(name = "PayWebServiceImplPort")
    public PayWebService getPayWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PayWebServiceImplPort, PayWebService.class, features);
    }

}
